#! /bin/sh
# XXX: The file MUST be executable (chmod +x bspwmrc)
# Refer: https://cn.linux-terminal.com/?p=1881

# 将默认的 X 光标更改为更熟悉的左指针
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
feh --bg-scale ~/.config/bspwm/wallpaper.jpg &
#~/.config/polybar/launch.sh
~/.config/polybar/launch.sh --blocks  # See: https://github.com/adi1090x/polybar-themes

# Chinese input method
#fcitx -d
#pgrep -x fcitx > /dev/null || fcitx -d
ibus-daemon -rxRd

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width         0
bspc config window_gap           6

#bspc config top_padding          5
#bspc config left_padding         5
#bspc config right_padding        5
#bspc config bottom_padding       5

#bspc config normal_border_color  \#FFFF00
#bspc config focused_border_color \#00FF00

bspc config split_ratio             0.5     # 窗口分隔比例
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false   # 当鼠标移动到窗口自动获得焦点

bspc rule -a Alacritty desktop='^1' follow=on state=floating center=true rectangle=1400x800+0+0
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a Chrome desktop='^3' follow=on
bspc rule -a Thunderbird desktop='^4' follow=on
bspc rule -a Clash desktop='^5' follow=on
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
